### PR TITLE
Fix name of pbooth.pub

### PR DESCRIPTION
**Pull request by philbooth**
Presumably these public keys are meant to match our account names in AWS? Mine didn't. And maybe that's why I've never been able to get `fxa-dev` working since I joined the team 3 years ago, lol.

@jbuck r?

### CODE REVIEW

**Comment by jbuck** [comment]
This seems fine to me, though I truthfully don't know if it'll help! 🙃

**Comment by jrgm** [comment]
Actually, revert this change. The filenname must end in `pub`.

**Comment by jrgm** [comment]
Also, FYI, the filename does not need to match your username. In fact, there is no ~pbooth or ~jrgm on these boxen. But the filename in this repo must end with '.pub'.

**Comment by philbooth** [comment]
> The filenname must end in `pub`.

Whoops, typo. My muscle memory for typing `pb` is deeply ingrained.

**Comment by jrgm** [comment]
Okay, so I see you changed the filename. Can you now do `ssh ec2-user@meta-latest.dev.lcip.org`?

If not, what is the output of `ssh-add -l` on your local client. (If more than five and this key is #6 or higher, you'll need to pick which key with `ssh -i /path/to/secretkey ec2-user@meta-latest.dev.lcip.org`.

**Comment by jrgm** [comment]
So something went wrong in the initial run of ansible by cloud-init.

@philbooth Can you ssh into the ec2 instance and look near the bottom of /var/log/cloud-init-output.log and see what the error was?

**Comment by jrgm** [comment]
Was there anything before that that failed? I'm not seeing the fundamental difference between how db_patcher.js is run in a circle env vs. how it run above.

Can you tear down the stack you built and then build again? See if it fails again?

**Comment by philbooth** [comment]
> Was there anything before that that failed?

Nope all the preceding tasks appear to finish successfully. I can provide the full log if it's helpful.

> Can you tear down the stack you built and then build again?

Is there a proper way to tear down the stack? I tried just running `make` again and got the same error, but suspect that isn't what you meant. Do I just go into the AWS console and terminate the instance, or is there some command for doing it cleanly or whatever?

**Comment by philbooth** [comment]
> Is there a proper way to tear down the stack?

Never mind, @shane-tomlinson pointed me at the CloudFormation bit of the AWS console, and I do indeed get the same error after tearing it down. But maybe there's something wrong with my feature branch, Shane got the same error when he tried to spin up a stack using it too.

Anyway, not to worry, I'm further on in the set-up than I was previously and can carry on poking around with my branch to try and figure it out from here. Thanks for your help!

**Comment by vladikoff** [comment]
Filed: https://github.com/mozilla/fxa-auth-db-mysql/issues/343

**Comment by jrgm** [comment]
@philbooth - can you try again. The mysql-patcher should be fixed now.

**Comment by jrgm** [comment]
Actually, there's fix needed in fxa-dev, where it tries to generate legacy keys for 123done and fails since the script has been removed now. Fixing...

**Comment by jrgm** [comment]
PR to fix fxa-dev in https://github.com/mozilla/fxa-dev/pull/363

**Comment by philbooth** [comment]
:+1: All good now, thanks both!

**Pull request merged**
